electricity:
  phone_number: ""
  password: ""
  deiver_impltcity_wait_time: 60
  retry_times_limit: 5
  login_expected_time: 60
  retry_wait_time_offset_unit: 10
  data_retention_days: 7
  ignore_user_id: []
  cron_hour: '7,19'

db:
  name: 'homeassistant.db'

logger:
  level: 'info'

data:
  path: '/data'

web:
  port: 8080